### ISSUE TITLE
epub to convert gets unicode decode error.

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.calibre#13]
I tried at edeposit-aplikace.nkp.cz to send GraphDatabase.epub
calibre got:
AMQPError(headers={'exception_type': "<type 'exceptions.UnicodeDecodeError'>", 'exception': '', 'traceback': 'Traceback (most recen\|#                               title = stateTitle,                                                                                  
t call last):\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 141, in onMessageReceived\n    uuid\n  F\|#                               stateClass = 'contentstate-'+plone_utils.normalizeString(state),                                     
ile "/usr/lib/python2.7/site-packages/edeposit/amqp/calibre/__init__.py", line 42, in reactToAMQPMessage\n    message.b64_data\n  F\|#                               )                                                                                                    
ile "/usr/lib/python2.7/site-packages/edeposit/amqp/calibre/calibre.py", line 60, in convert\n    sh.ebook_convert(ifile.name, ofil\|#         return                                                                                                                     
ename).__str__(),\n  File "/usr/lib/python2.7/site-packages/sh.py", line 409, in __str__\n    else: return unicode(self).encode(sel\|
f.call_args["encoding"])\n  File "/usr/lib/python2.7/site-packages/sh.py", line 414, in __unicode__\n    self.call_args["decode_err\|class ContentState(grok.Viewlet):
ors"])\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc2 in position 268: ordinal not in range(128)', 'exception_name': \|    grok.name('edeposit.contentstate')
'UnicodeDecodeError', 'UUID': '{"context_UID": "c25ef31b137242beb36a3968de60a257", "session_data": {"msg": "", "isbn": "None", "fil\|    grok.require('zope2.View')
ename": "GraphDatabases.epub"}}'}, exception='', payload="'ascii' codec can't decode byte 0xc2 in position 268: ordinal not in rang\|    grok.viewletmanager(IContentViews)
e(128)", exception_name='UnicodeDecodeError')

**Comment by Bystroushaak** [comment]
I've just released new version of the package - v1.1.3.
